### ISSUE TITLE
Homepage is a 404

### ISSUE THREAD

**Issue by zepstein** [TULiberalArts/American-Studies#3]

**Comment by tu-chill** [comment]
can not reproduce.
What url are you looking at?

**Comment by tu-chill** [comment]
https://develop.cla.temple.edu/american-studies/

production site is still up but dev site is down

**Comment by tu-chill** [comment]
I looked at this, and obviously, I'm missing something @LabLayers @lidopaglia can you take a look when you have a chance?

**Comment by lidopaglia** [comment]
fixed in https://github.com/TULiberalArts/American-Studies/commit/2227dc996e45f66a9f03553ac8eb18045c52c3d9
