### ISSUE TITLE
_config.yml | program Information

### ISSUE THREAD

**Issue by tu-chill** [TULiberalArts/American-Studies#6]
Update Values in the config for the program. If not able to find file or not sure how to make changes 

1. Provide values as comment in this issue
2. Reach out to Camille or Chris so we can show you how for next time

# Program Information
# Short tagline for tweets (<100 characters)
tagline: This is our life's work
# Longer descriptions for link previews (<250 characters)
description: 'Example of what the TU Theme will look like and all the wiz-bang things it can do. This Static Site was generated with Jekyll.'
# List of related keywords for search engines
keywords: highered, college, university, philadelphia, Temple

**Comment by CVE82** [comment]
Inserted telephone dashes, descriptions and email code into each program config file

**Comment by CVE82** [comment]
Inserted telephone dashes, descriptions and email code into each program config file
